package:
  name: yt
  version: 3.3.dev0

source:
  hg_url: http://bitbucket.org/yt_analysis/yt

build:
  entry_points:
    - yt = yt.utilities.command_line:run_main

requirements:
  build:
    - python
    - numpy
    - cython 0.22*
    - setuptools 
    - libpython # [win]
    - mingw # [win]
  run:
    - python
    - numpy
    - h5py
    - matplotlib
    - ipython
    - sympy

test:
  requires:
    - nose
  commands:
    - yt -h
  imports:
    - yt

about:
  home: http://yt-project.org/
  license: BSD
