package:
  name: yt
  version: 2.5.5

source:
  hg_url: http://bitbucket.org/yt_analysis/yt

build:
  entry_points:
    - yt = yt.utilities.command_line:run_main

requirements:
  build:
    - python
    - numpy
    - cython 0.19*
    - libpng
    - freetype
    - hdf5
    - distribute
  run:
    - python
    - numpy
    - libpng
    - freetype
    - hdf5
    - h5py
    - matplotlib
    - ipython
    - ipython-notebook
    - ipython-qtconsole
    - tornado
    - pyzmq
    - jinja2
    - pygments
    - sphinx

test:
  commands:
    - yt --help
  imports:
    - yt
    - yt.utilities.hdf5_light_reader

about:
  home: http://yt-project.org/
  license: GNU General Public License version 3 (GPL)
