package:
  name: yt

source:
  hg_url: https://bitbucket.org/yt_analysis/yt
  hg_tag: yt

build:
  entry_points:
    - yt = yt.utilities.command_line:run_main

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools 
    - libpython # [win]
    - mingw # [win]
    - pyembree
  run:
    - python
    - numpy
    - h5py
    - sympy
    - matplotlib
    - ipykernel
    - ipython
    - pyembree

test:
  requires:
    - nose
  commands:
    - yt -h
  imports:
    - yt

about:
  home: http://yt-project.org/
  license: BSD
  license_file: COPYING.txt
